version: '3.8'

services:
  web:
    build: .
    command: gunicorn --bind 0.0.0.0:8000 main.wsgi:application
    volumes:
      - .:/app
      - static_volume:/app/static
    expose:
      - 8000
    environment:
      - DEBUG=1

  nginx:
    image: nginx:1.21-alpine
    ports:
      - "80:80"
    volumes:
      - static_volume:/app/static
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - web

volumes:
  postgres_data:
  static_volume:
