# Generated by Django 5.0.4 on 2024-04-26 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('github_getter', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='githubrepository',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
