# Generated by Django 5.0.4 on 2024-04-27 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('github_getter', '0002_alter_githubrepository_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='githubrepository',
            name='description',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
