# Generated by Django 5.0.4 on 2024-04-27 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('github_getter', '0003_alter_githubrepository_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='githubrepository',
            name='language',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
